"""Initial migration

Revision ID: 23edf4112cc2
Revises: 
Create Date: 2026-04-25 17:14:01.155626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23edf4112cc2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_checkpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('checkpoint_number', sa.Integer(), nullable=False),
    sa.Column('last_entry_hash', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkpoint_number')
    )
    op.create_index('idx_checkpoint_number', 'ledger_checkpoints', ['checkpoint_number'], unique=False)
    op.create_table('token_blacklist',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_blacklist_jti'), 'token_blacklist', ['jti'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hardware_mfa_required', sa.Boolean(), nullable=False),
    sa.Column('quota_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('mfa_secret', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entry_number', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('previous_hash', sa.Text(), nullable=False),
    sa.Column('entry_hash', sa.Text(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_number')
    )
    op.create_index('idx_audit_action', 'audit_log', ['action'], unique=False)
    op.create_index('idx_audit_actor', 'audit_log', ['actor_id'], unique=False)
    op.create_index('idx_audit_request_id', 'audit_log', ['request_id'], unique=False)
    op.create_index('idx_audit_resource', 'audit_log', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_log', ['timestamp'], unique=False)
    op.create_table('hardware_token_credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('credential_id', sa.Text(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('token_type', sa.String(length=16), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hwcred_cid', 'hardware_token_credentials', ['credential_id'], unique=False)
    op.create_index('idx_hwcred_user', 'hardware_token_credentials', ['user_id'], unique=False)
    op.create_table('key_rotation_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('key_type', sa.String(length=16), nullable=False),
    sa.Column('old_key_id', sa.String(length=64), nullable=True),
    sa.Column('new_key_id', sa.String(length=64), nullable=False),
    sa.Column('affected_records', sa.Integer(), nullable=False),
    sa.Column('rotated_at', sa.DateTime(), nullable=False),
    sa.Column('rotated_by', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['rotated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('blob_path', sa.Text(), nullable=False),
    sa.Column('cipher_name', sa.String(length=32), nullable=False),
    sa.Column('master_key_id', sa.String(length=64), nullable=True),
    sa.Column('encrypted_dek', sa.JSON(), nullable=False),
    sa.Column('integrity_token', sa.JSON(), nullable=False),
    sa.Column('searchable_indices', sa.JSON(), nullable=True),
    sa.Column('he_fields', sa.JSON(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('previous_version_id', sa.String(length=36), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['previous_version_id'], ['records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_records_content_type', 'records', ['content_type'], unique=False)
    op.create_index('idx_records_deleted', 'records', ['is_deleted'], unique=False)
    op.create_index('idx_records_deleted_at', 'records', ['deleted_at'], unique=False)
    op.create_index('idx_records_owner', 'records', ['owner_id'], unique=False)
    op.create_table('replication_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('endpoint_url', sa.String(length=512), nullable=False),
    sa.Column('auth_token_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rep_nodes_status', 'replication_nodes', ['status'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('refresh_token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record_acls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('permission', sa.String(length=16), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('granted_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('replication_dead_letter',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('metadata_snapshot', sa.JSON(), nullable=False),
    sa.Column('blob_checksum', sa.String(length=64), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('error_history', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['replication_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dl_node', 'replication_dead_letter', ['node_id'], unique=False)
    op.create_index('idx_dl_record', 'replication_dead_letter', ['record_id'], unique=False)
    op.create_table('replication_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('blob_checksum', sa.String(length=64), nullable=False),
    sa.Column('metadata_snapshot', sa.JSON(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['replication_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_replog_node', 'replication_log', ['node_id'], unique=False)
    op.create_index('idx_replog_seq', 'replication_log', ['sequence_number'], unique=False)
    op.create_index('idx_replog_status', 'replication_log', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_replog_status', table_name='replication_log')
    op.drop_index('idx_replog_seq', table_name='replication_log')
    op.drop_index('idx_replog_node', table_name='replication_log')
    op.drop_table('replication_log')
    op.drop_index('idx_dl_record', table_name='replication_dead_letter')
    op.drop_index('idx_dl_node', table_name='replication_dead_letter')
    op.drop_table('replication_dead_letter')
    op.drop_table('record_acls')
    op.drop_table('sessions')
    op.drop_index('idx_rep_nodes_status', table_name='replication_nodes')
    op.drop_table('replication_nodes')
    op.drop_index('idx_records_owner', table_name='records')
    op.drop_index('idx_records_deleted_at', table_name='records')
    op.drop_index('idx_records_deleted', table_name='records')
    op.drop_index('idx_records_content_type', table_name='records')
    op.drop_table('records')
    op.drop_table('key_rotation_log')
    op.drop_index('idx_hwcred_user', table_name='hardware_token_credentials')
    op.drop_index('idx_hwcred_cid', table_name='hardware_token_credentials')
    op.drop_table('hardware_token_credentials')
    op.drop_index('idx_audit_timestamp', table_name='audit_log')
    op.drop_index('idx_audit_resource', table_name='audit_log')
    op.drop_index('idx_audit_request_id', table_name='audit_log')
    op.drop_index('idx_audit_actor', table_name='audit_log')
    op.drop_index('idx_audit_action', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_index(op.f('ix_token_blacklist_jti'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_index('idx_checkpoint_number', table_name='ledger_checkpoints')
    op.drop_table('ledger_checkpoints')
    # ### end Alembic commands ###
